export default function(){
  return [
    {name:'Бары 1', type: 'type_1'},
    {name:'Вендинг', type: 'type_2'},
    {name:'Винные', type: 'type_3'},
    {name:'Винодельни', type: 'type_4'},
    {name:'Гостиницы', type: 'type_5'},
    {name:'Кальянные', type: 'type_6'},
    {name:'Кафе', type: 'type_7'},
    {name:'Кейтеринг', type: 'type_8'},
    {name:'Клубы', type: 'type_9'},
    {name:'Кондитерские', type: 'type_10'},
    {name:'Кофейни', type: 'type_11'},
    {name:'Отели', type: 'type_12'},
    {name:'Пекарни', type: 'type_13'},
    {name:'Пивные', type: 'type_14'},
    {name:'Пищевые заводы', type: 'type_15'},
    {name:'Пиццерии', type: 'type_16'},
    {name:'Развлечения', type: 'type_17'},
    {name:'Реклама', type: 'type_18'},
    {name:'Рестораны', type: 'type_19'},
    {name:'Сыроварни', type: 'type_20'},
    {name:'Фаст Фуд', type: 'type_21'},
    {name:'Франчайзинг', type: 'type_22'},
    {name:'Частные Фермы', type: 'type_23'},
  ]
} 
